version: '2'
services:
    nginx:
        depends_on: 
            - phpfpm
        image: nginx:1.18
        ports: 
            - "81:81"
        restart: always
        volumes: 
            # - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/sites-available/default.conf
            - ./docker/nginx/default.conf:/etc/nginx/sites-enabled/default.conf
            - ./docker/nginx/log/nginx-access.log:/var/log/nginx/access.log
            - ./docker/nginx/log/nginx-error.log:/var/log/nginx/error.log
        links: 
            - phpfpm
    phpfpm:
        image: php:7.4-fpm
        restart: always
        working_dir: /var/www/html
        ports: 
            - "9001:9001"
        volumes: 
            # - .:/var/www/html
            # - ./docker/php_fpm:/etc/php/7.4/fpm
            - ./docker/php:/usr/share/nginx/html
        depends_on: 
            - mysql
        links: 
            - mysql
    mysql:
        image: mysql  
        restart: always
        container_name: db
        ports: 
            - "3308:3308"
        volumes: 
            - ./docker/mysql:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: "05052000"
            MYSQL_DATABASE: "magento2"
            MYSQL_USER: "trinhthikim"
            MYSQL_PASSWORD: "05052000"
        links: 
            - elasticsearch
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        container_name: elasticsearch
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ulimits: 
            memlock:
                soft: -1
                hard: -1
        volumes: 
            - ./docker/elasticsearch:/usr/share/elasticsearch/
        ports:
            - "9200:9200"

    # build: .
    # dockerfile: ./docker/Dockerfile
    # container_name: magento2
    # working_dir: /var/www/html
    # ports: 
    #     - "81:81"
    # volumes: 
        
    # links: 
    #     - mysql


